-- ============================================================
-- FanFinity  |  Seed Data
-- Run this file AFTER fanfinity_final_schema.sql
-- Adds all products into the products table
--
-- How to run:
--   Open pgAdmin → select fanfinity DB → Query Tool
--   Open this file → press F5
--
-- Category IDs (from our schema):
--   1 = Anime
--   2 = Games
--   3 = Music
--   4 = Movies
--   5 = Series
--   6 = Kpop      (sub of Music)
--   7 = Pop        (sub of Music)
--   8 = Movies & Series
-- ============================================================


-- ============================================================
-- SECTION 1: GAMING PRODUCTS  (category_id = 2)
-- Images: images/products/games/1.jpg to 21.jpg
-- Total : 21 products
-- ============================================================

INSERT INTO products (product_name, category_id, key_words, description, specifications, ideal_for, price, mrp, discount, rating, reviews, image_link, stock, is_new, is_popular, is_recommended, show_on_home) VALUES

('Gamer Controller LED Lamp',        2, 'Gaming Controller Neon Desk Lamp',                'Stylish LED lamp designed with gaming controller icons. Perfect ambient light for gaming desks, streaming setups, or bedroom decor.',              'Material: Acrylic Panel + LED Base | Lighting: Multicolor RGB LED | Power Source: USB (5V) | Lamp Height: ~20 cm | Base Diameter: ~10 cm | Glow Effect: Edge-lit acrylic with controller icon design',                                    'Gamers, gaming room decor, streamers',          799.00,  1299.00, 38, 4.6, 820,  'images/products/games/1.jpg',  50, TRUE,  TRUE,  FALSE, TRUE),

('PS5 Controller Wooden Stand',      2, 'PlayStation Controller & Headset Organizer',      'Premium wooden desk stand for PlayStation controllers and headphones. Keeps gaming gear organized while adding a minimal aesthetic to the desk.',  'Material: Premium Solid Wood | Finish: Smooth hand-polished | Controller Slots: 2 | Headset Hook: 1 integrated top hook | Dimensions: ~30 x 12 x 18 cm | Weight: ~400 g | Non-slip rubber base pads',                                     'Console gamers, desk organizers',               999.00,  1599.00, 38, 4.5, 640,  'images/products/games/2.jpg',  45, FALSE, FALSE, FALSE, FALSE),

('PlayStation Controller Holder',    2, 'Dual Controller Gaming Stand',                    'Compact wooden stand designed to hold multiple PlayStation controllers. Helps keep gaming accessories tidy and easily accessible.',                 'Material: Engineered MDF Wood | Slots: 2-3 controller cradles | Finish: Matte lacquer | Dimensions: ~25 x 10 x 15 cm | Weight: ~300 g | Scratch-resistant surface coating',                                                               'PlayStation gamers',                            899.00,  1499.00, 40, 4.4, 510,  'images/products/games/3.jpg',  60, FALSE, FALSE, FALSE, FALSE),

('Minecraft Pixel Mug',              2, 'Minecraft Pixel Art Coffee Mug',                  'Ceramic mug inspired by Minecraft pixel graphics. Perfect for coffee, tea, or gaming breaks with your favorite blocky characters.',               'Material: High-grade Ceramic | Capacity: 350 ml | Print: Wraparound high-res pixel art | Care: Dishwasher and microwave safe | Handle: Ergonomic C-handle | Weight: ~320 g',                                                               'Minecraft fans, gamers',                        599.00,  999.00,  40, 4.6, 420,  'images/products/games/4.jpg',  70, FALSE, TRUE,  FALSE, TRUE),

('Retro Gaming Coins',               2, 'Old School Gaming Collectible Coins',             'Vintage-style metal coins featuring nostalgic gaming messages like One More Game and Go To Bed. A perfect collector item for retro gaming fans.',   'Material: Zinc Alloy Metal | Finish: Antique bronze plating | Diameter: ~4 cm per coin | Thickness: ~3 mm | Pack: Set of 4 coins | Design: Double-sided engraved typography | Weight: ~80 g per coin',                                     'Collectors, retro gamers',                      499.00,  899.00,  44, 4.5, 310,  'images/products/games/5.jpg',  90, FALSE, FALSE, FALSE, FALSE),

('Game Boy Retro Keychain',          2, 'Classic Game Boy Keychain',                       'Mini Game Boy inspired keychain perfect for retro gaming lovers. A compact collectible that clips right onto your bag or keys.',                  'Material: ABS Hard Plastic + Metal split ring | Size: ~6 cm length | Finish: Painted matte surface | Detail: Button and screen replica print | Ring diameter: 2.5 cm | Weight: ~20 g',                                                     'Retro gamers, keychain collectors',             399.00,  699.00,  43, 4.4, 280,  'images/products/games/6.jpg',  100, FALSE, FALSE, FALSE, FALSE),

('Anime Cinema Keychains',           2, 'Anime Style Cinema Keychain Set',                 'Stylish anime-themed keychains designed like cinema tickets with vibrant prints. A fun accessory for any anime and gaming fan.',                   'Material: Premium Acrylic | Finish: Glossy UV print | Size: ~7 x 3 cm each | Pack: 2 pieces | Attachment: Metal keyring | Thickness: 3 mm | Print: Double-sided design',                                                                  'Anime fans, collectors',                        449.00,  799.00,  44, 4.3, 260,  'images/products/games/7.jpg',  120, FALSE, FALSE, FALSE, TRUE),

('Sonic Character Keychains',        2, 'Sonic Gaming Keychain Set',                       'Fun keychains featuring classic Sonic characters, perfect for bags and keys. Soft rubber design with accurate Sonic character details.',           'Material: Soft PVC Rubber | Characters: Sonic, Tails, Knuckles | Size: ~5-6 cm each | Finish: Vibrant color print | Pack: 2-3 keychains | Attachment: Metal split ring',                                                                   'Sonic fans, gamers',                            349.00,  699.00,  50, 4.5, 350,  'images/products/games/8.jpg',  110, FALSE, FALSE, FALSE, FALSE),

('RGB Gaming PC Case',               2, 'Transparent RGB Gaming PC Case',                  'High-end transparent PC case with RGB lighting support for custom gaming builds. Full tempered glass side panels for a showcase build.',          'Form Factor: ATX Mid-Tower | Side Panel: 4-side tempered glass | RGB: 3 pre-installed ARGB fans | Drive Bays: 2x 3.5in + 2x 2.5in | I/O Panel: USB 3.0 x2, USB-C x1, HD Audio | Dimensions: 45 x 22 x 48 cm | Weight: ~7 kg',           'PC gamers, custom PC builders',                 6999.00, 9999.00, 30, 4.7, 150,  'images/products/games/9.jpg',  25, TRUE,  FALSE, TRUE,  TRUE),

('Futuristic Transparent PC Case',   2, 'Luxury Gaming PC Cabinet',                        'Premium cube-style gaming cabinet designed for aesthetic builds and RGB showcase setups with panoramic glass on all sides.',                      'Form Factor: ITX/mATX Cube | Panel: Full panoramic tempered glass | Cooling: Top + bottom mesh vents | GPU Support: up to 320 mm | Radiator Support: 240 mm front | Dimensions: 35 x 35 x 40 cm | Weight: ~6 kg | Aluminum frame',          'Pro gamers, PC enthusiasts',                    8999.00, 12999.00, 31, 4.8, 120,  'images/products/games/10.jpg', 20, FALSE, TRUE,  FALSE, FALSE),

('Ergonomic Gaming Chair Red',       2, 'Racing Style Gaming Chair',                       'Comfortable racing-style gaming chair with ergonomic lumbar support, adjustable height, and full recline feature for long gaming sessions.',      'Material: Premium PU Leather | Foam Density: High-density cold foam | Armrest: 4D adjustable | Height Adjustment: Gas lift 45-53 cm | Recline: 90-155 degrees | Max Load: 150 kg | Weight: ~22 kg | Color: Red + Black',                    'Gamers, office setup',                          9999.00, 14999.00, 33, 4.6, 540,  'images/products/games/11.jpg', 35, FALSE, TRUE,  TRUE,  TRUE),

('Premium Black Gaming Chair',       2, 'Executive Gaming Chair',                          'Minimalist all-black ergonomic chair designed for long gaming or work sessions with a clean executive look and premium lumbar support.',          'Material: High-grade PU Leather | Foam: Memory foam headrest and lumbar | Armrest: 2D adjustable | Height Range: 44-52 cm | Recline: 90-150 degrees | Swivel: 360 degree | Max Load: 130 kg | Weight: ~20 kg | Color: All Black',           'Gamers, office workers',                        8999.00, 13999.00, 36, 4.5, 460,  'images/products/games/12.jpg', 30, FALSE, FALSE, FALSE, FALSE),

('Pro Gamer Hoodie',                 2, 'Gaming Graphic Hoodie',                           'Comfortable hoodie featuring bold Pro Gamer graphic print on the front. Perfect for casual wear, late-night gaming sessions, and gifting.',       'Material: 60% Cotton + 40% Polyester blend | Fit: Regular unisex | Print: Screen-printed front graphic | Pocket: Front kangaroo pocket | Hood: Adjustable drawstring | Sizes: S to XXL | Care: Machine wash cold',                         'Gamers, casual wear',                           1199.00, 1999.00, 40, 4.4, 370,  'images/products/games/13.jpg', 80, FALSE, FALSE, FALSE, TRUE),

('Eat Sleep Anime Gaming T-Shirt',   2, 'Anime Gamer Graphic T-Shirt',                     'Trendy T-shirt with Eat Sleep Anime Gaming Repeat graphic design. A must-have casual tee for fans who love both anime and gaming.',              'Material: 100% Ring-spun Cotton | Weight: 180 GSM | Fit: Regular unisex | Print: Screen-printed chest graphic | Neckline: Classic crew neck | Sizes: S to XXL | Care: Machine wash cold, do not bleach',                                   'Anime lovers, gamers',                          699.00,  1199.00, 42, 4.5, 520,  'images/products/games/14.jpg', 100, FALSE, FALSE, TRUE,  TRUE),

('Gamer Hoodie',                     2, 'Think Sleep Game Hoodie',                         'Stylish hoodie designed for gamers who love minimal gaming graphics. Features a bold Think Sleep Game Repeat print on the chest.',               'Material: Cotton Fleece 80/20 blend | Weight: 320 GSM | Fit: Slightly oversized | Print: Minimal chest print | Pocket: Kangaroo front pocket | Cuffs: Ribbed elastic | Sizes: S to XXL | Care: Cold wash inside out',                      'Gamers, casual wear',                           1099.00, 1799.00, 39, 4.4, 340,  'images/products/games/15.jpg', 75, TRUE,  FALSE, FALSE, FALSE),

('Minecraft Plush Toy Set',          2, 'Minecraft Plush Characters Set',                  'Cute plush toys featuring iconic Minecraft characters. Soft, huggable, and safe for all ages. Perfect for collectors and kids alike.',           'Material: Ultra-soft polyester plush + PP cotton fill | Characters: Creeper, Steve, Enderman, Pig | Height: ~20 cm each | Safety: CE certified, child-safe materials | Pack: 4 characters | Washable: Yes',                                  'Minecraft fans, kids',                          1499.00, 2199.00, 32, 4.6, 410,  'images/products/games/16.jpg', 55, FALSE, TRUE,  FALSE, TRUE),

('PlayStation LED Wall Panels',      2, 'PlayStation Icon LED Light Panels',               'Hexagonal LED wall lights featuring PlayStation symbols. Modular design lets you create custom wall patterns for the ultimate gaming setup.',     'Material: ABS Plastic panels + LED strips | Panel Shape: Hexagonal | Power: USB + controller | Colors: 16 million RGB colors | Pack: 6 panels + connecting cables | Installation: Adhesive mount | Smart: App-controlled brightness',      'Gamers, room decor',                            1999.00, 2999.00, 33, 4.7, 300,  'images/products/games/17.jpg', 40, TRUE,  TRUE,  TRUE,  TRUE),

('PlayStation Neon Desk Light',      2, 'PlayStation RGB Neon Lamp',                       'RGB neon desk lamp with PlayStation controller and button icons. Creates a vibrant pink-purple gaming atmosphere for your desk or shelf.',        'Material: Flexible LED neon tube + acrylic backing | Colors: Pink, Purple, Multicolor modes | Power: USB 5V | Dimensions: ~30 x 20 cm | Brightness: Dimmable 3 levels | Mount: Freestanding or wall mount | Switch: Touch on/off',         'PlayStation fans, gamers',                      1299.00, 1999.00, 35, 4.6, 450,  'images/products/games/18.jpg', 60, FALSE, FALSE, FALSE, FALSE),

('Gaming Love Decor Light',          2, 'LOVE Gaming LED Lamp',                            'Creative LED lamp combining LOVE typography with a gaming controller replacing the letter O. A quirky and stylish decor piece for any gamer.',   'Material: Acrylic Panel + Wooden Base + LED | Power: USB 5V | Glow: Warm white edge-lit effect | Dimensions: ~22 x 10 cm | Switch: Push button on base | Base finish: Natural wood grain | Cord length: 1.2 m',                           'Gamers, room decor',                            899.00,  1499.00, 40, 4.5, 280,  'images/products/games/19.jpg', 70, FALSE, FALSE, FALSE, FALSE),

('Gamer LED Night Lamp',             2, 'Minimal Gamer Icon Lamp',                         'Modern LED lamp featuring a gamer silhouette icon sitting at a desk. Clean minimal design that fits into any gaming or study room setup.',       'Material: Acrylic Panel + ABS Base + LED | Silhouette: Gamer at desk icon | Power: USB 5V | Height: ~18 cm | Glow: Cool white edge-lit | Switch: Slide on/off on base | Cord: 1 m USB cable',                                             'Gamers, desk decor',                            799.00,  1299.00, 38, 4.4, 310,  'images/products/games/20.jpg', 85, FALSE, FALSE, FALSE, FALSE),

('PlayStation Wall Shelf',           2, 'Gaming Controller Floating Shelf',                'Decorative floating shelf shaped like a PlayStation controller split into two halves. Mounts on wall to display games, figures, or accessories.', 'Material: MDF board + metal wall brackets | Shape: Split PS controller halves | Load Capacity: ~3 kg per shelf | Shelf Depth: 8 cm | Width: ~40 cm per piece | Finish: Matte painted | Hardware: Screws and wall anchors included',       'Gaming room decor',                             1599.00, 2499.00, 36, 4.5, 260,  'images/products/games/21.jpg', 50, FALSE, FALSE, TRUE,  TRUE);


-- ============================================================
-- SECTION 2: ANIME PRODUCTS  (category_id = 1)
-- Images: images/products/anime/1.jpg to 21.jpg
-- Total : 21 products
-- ============================================================

INSERT INTO products (product_name, category_id, key_words, description, specifications, ideal_for, price, mrp, discount, rating, reviews, image_link, stock, is_new, is_popular, is_recommended, show_on_home) VALUES

('Anime Character Keychain Set',      1, 'Anime Character Metal Keychain Set | Otaku Accessories | Collectible Key Rings',       'A stylish collection of anime-inspired character keychains featuring vibrant prints and durable metal rings. Perfect for backpacks, keys, or gifting.',                    'Material: Acrylic faceplate + Zinc alloy metal ring | Print: UV gloss-coated character art | Size: ~5-7 cm each | Pack: Set of 6 keychains | Ring diameter: 2.5 cm | Thickness: 4 mm | Weight: ~15 g per piece',                               'Anime fans, backpack accessories, gifting',     399.00,  699.00,  43, 4.5, 620,  'images/products/anime/1.jpg',  50, FALSE, FALSE, FALSE, TRUE),

('Anime Strap Keychain Collection',   1, 'Anime Character Strap Keychain Set | Kawaii Bag Accessories',                         'Colorful wrist-strap keychains featuring adorable anime character charms. Lightweight and durable for bags, keys, or phone straps.',                                       'Material: Soft PVC charm + braided nylon strap | Strap Length: ~10 cm | Charm Size: ~4 cm | Clip: Metal lobster clasp | Pack: Set of 4 | Weight: ~10 g per piece | Colors: Multiple vibrant options',                                         'Anime fans, students, collectors',              349.00,  649.00,  46, 4.4, 510,  'images/products/anime/2.jpg',  45, FALSE, FALSE, FALSE, FALSE),

('Anime Fire Effect LED Lamp',        1, 'Anime Action LED Night Lamp | Anime Desk Decor Light',                                'Dramatic anime battle scene with a glowing fire effect. Creates an exciting fiery display for desks or shelves with warm orange-red illumination.',                        'Material: Premium Acrylic Panel + ABS LED Base | Effect: Fire-glow warm orange LED | Power: USB 5V | Height: ~18 cm | Base: Weighted non-slip black base | Switch: Touch-sensitive on base | Cord: 1.2 m USB',                                'Anime collectors, room decor, gaming setups',   799.00,  1299.00, 38, 4.6, 820,  'images/products/anime/3.jpg',  49, TRUE,  TRUE,  FALSE, TRUE),

('Anime Desk Decor Lamp Figure',      1, 'Anime Character Desk Lamp Figure | Decorative Anime Table Light',                    'A charming anime figure sitting under a small glowing lamp. Combines artistic resin sculpture with functional desk lighting in one elegant piece.',                        'Material: Hand-painted Resin figure + LED lamp | Power: USB 5V | Height: ~15 cm | Light color: Warm white 3000K | Figure detail: Hand-painted with matte finish | Base: Circular weighted resin base | Cord: 1 m',                           'Anime lovers, desk decor, collectors',          749.00,  1199.00, 37, 4.5, 430,  'images/products/anime/4.jpg',  40, FALSE, FALSE, FALSE, FALSE),

('Anime Headphone Stand Figure',      1, 'Anime Character Headphone Stand | Desk Organizer Figure',                            'An anime character stand designed to hold headphones while adding personality to your workspace. The character pose creates a natural headphone cradle.',                   'Material: High-quality PVC figure | Height: ~22 cm | Base: Weighted stable platform ~12 cm diameter | Headphone cradle: Rounded top arm | Max headphone width: 20 cm | Surface: Scratch-resistant painted finish | Weight: ~250 g',          'Gamers, anime fans, desk setups',               899.00,  1499.00, 40, 4.7, 560,  'images/products/anime/5.jpg',  38, TRUE,  TRUE,  TRUE,  TRUE),

('Anime LED Acrylic Lamp',            1, 'Anime LED Acrylic Night Lamp | Anime Room Decor Light',                               'A laser-etched acrylic LED lamp featuring a detailed anime-style scene that glows beautifully in dark environments. Clean minimal design.',                                'Material: 5 mm crystal-clear Acrylic + LED Base | Etching: Laser-precision engraved artwork | Light: Warm white 3000K glow | Power: USB 5V | Height: ~20 cm | Base: Black ABS with on/off switch | Multiple brightness modes',             'Bedroom decor, anime fans, gifting',            699.00,  1199.00, 42, 4.5, 480,  'images/products/anime/6.jpg',  42, FALSE, FALSE, FALSE, TRUE),

('Anime Character LED Light Lamp',    1, 'Anime Character Edge-Lit Acrylic Lamp | Anime Night Light',                          'An eye-catching LED lamp showcasing a detailed anime character outline with bright cool-white edge illumination and a modern minimalist base.',                             'Material: 6 mm Acrylic Panel + ABS Base | Character: Full body anime silhouette edge-lit design | Light: Cool white 6000K LED | Power: USB | Height: ~20 cm | Brightness: 3-level dimmer switch | Base: Matte black finish',               'Anime fans, collectors, night lights',          749.00,  1249.00, 40, 4.6, 390,  'images/products/anime/7.jpg',  36, FALSE, FALSE, FALSE, FALSE),

('Anime Logo LED Lamp',               1, 'Anime Logo LED Night Lamp | Anime Desk Decoration',                                  'A glowing LED lamp featuring an iconic anime logo design. Adds a dramatic red glow perfect for anime display setups and gaming rooms.',                                    'Material: Acrylic Panel + ABS LED Base | Glow Color: Vivid Red LED | Power: USB 5V | Height: ~17 cm | Logo: Laser-etched on premium acrylic | Switch: Slide on base | Base: Heavy matte black plastic | Cord: 1 m',                        'Anime room decor, collectors',                  699.00,  1099.00, 36, 4.6, 720,  'images/products/anime/8.jpg',  44, FALSE, TRUE,  FALSE, TRUE),

('Anime Theme Cushion Cover',         1, 'Anime Printed Cushion Cover | Otaku Room Decor Pillow Case',                          'Soft cushion cover featuring cute anime character prints. Brings personality and otaku charm to your sofa, bed, gaming chair, or reading nook.',                           'Material: 100% Polyester microfiber fabric | Size: 40 x 40 cm | Print: All-over sublimation print | Closure: Concealed zip with anti-slip slider | Thread count: 200TC | Care: Machine washable cold | Weight: ~120 g',                     'Home decor, anime fans, bedrooms',              299.00,  599.00,  50, 4.4, 350,  'images/products/anime/9.jpg',  60, FALSE, FALSE, FALSE, FALSE),

('Anime Earbud Protective Case',      1, 'Anime Character Earbud Case | Protective AirPods Cover',                             'A durable protective case featuring anime artwork. Designed to protect AirPods or similar earbuds while adding a stylish anime flair to your accessories.',               'Material: Hard EVA shell with soft inner lining | Compatibility: AirPods Gen 1/2/3 and similar cases | Drop protection: 1.2 m tested | Keychain loop: Metal D-ring | Print: Full-wrap anime artwork | Dimensions: ~7 x 5 x 3 cm',           'Tech accessories, anime fans',                  349.00,  699.00,  50, 4.5, 410,  'images/products/anime/10.jpg', 55, FALSE, FALSE, FALSE, FALSE),

('Anime Shuriken Keychain Set',       1, 'Anime Ninja Shuriken Keychain Set | Metal Anime Accessories',                        'Unique ninja-style shuriken keychains inspired by anime aesthetics. Lightweight metal design with sharp detailing, safe for everyday carry.',                              'Material: Zinc alloy metal | Finish: Brushed silver + black enamel | Size: ~6 cm diameter | Edge: Blunted decorative edge | Pack: Set of 3 designs | Ring: Stainless steel split ring | Weight: ~35 g per piece',                           'Anime collectors, cosplay accessories',         399.00,  799.00,  50, 4.6, 580,  'images/products/anime/11.jpg', 52, FALSE, FALSE, TRUE,  FALSE),

('Anime Mini Character Figure Set',   1, 'Anime Mini Figure Collection | Cute Desk Display Figures',                           'A collection of adorable mini anime characters perfect for desk, shelf, or manga collection displays. Highly detailed at a small scale.',                                  'Material: High-quality PVC plastic | Height: ~6-8 cm per figure | Detail: Hand-painted facial and outfit details | Base: Individual flat circular display base | Pack: Set of 6 figures | Weight: ~30-50 g each | Finish: Semi-gloss',        'Collectors, anime fans, desk decor',            899.00,  1499.00, 40, 4.7, 690,  'images/products/anime/12.jpg', 35, TRUE,  TRUE,  TRUE,  TRUE),

('Anime Dark Warrior Statue',         1, 'Anime Dark Warrior Collectible Statue | Premium Figure',                              'Highly detailed anime warrior statue with a dynamic battle pose. Hand-painted with premium sculpting techniques for serious collectors and display enthusiasts.',           'Material: Cold-cast Polyresin | Height: ~25 cm | Base: Themed scenic display base | Paint: Hand-applied multi-layer paint job | Detail: Fine texture on armor and weapon | Weight: ~550 g | Packaging: Foam-protected collector box',        'Collectors, anime displays',                    2499.00, 3999.00, 38, 4.8, 210,  'images/products/anime/13.jpg', 18, TRUE,  FALSE, TRUE,  TRUE),

('Anime Demon Throne Figure',         1, 'Anime Demon Throne Figure | Fantasy Anime Statue',                                   'A dramatic anime villain figure seated on an ornate throne. Intricate detailing on the throne armrests and cape, ideal for premium display collections.',                 'Material: Premium Resin + PVC parts | Height: ~24 cm including throne | Throne: Detailed carved armrests with skulls and runes | Paint: Multi-tone wash with shadow effect | Weight: ~480 g | Box: Foam collector box',                    'Collectors, anime enthusiasts',                 2299.00, 3799.00, 39, 4.7, 180,  'images/products/anime/14.jpg', 15, FALSE, TRUE,  FALSE, FALSE),

('Anime Fire Warrior Statue',         1, 'Anime Fire Warrior Action Statue | Premium Collectible',                              'Dynamic anime warrior statue surrounded by sculpted flame effects. Designed for high-end collectors who want premium display-quality figures.',                            'Material: ABS Resin body + flexible PVC flame effects | Height: ~26 cm | Flames: Translucent orange-red sculpted PVC | Base: Scenic lava-crack textured base | Paint: Airbrush gradient finish | Weight: ~600 g',                          'Anime collectors, display shelves',             2699.00, 4199.00, 36, 4.8, 160,  'images/products/anime/15.jpg', 12, FALSE, FALSE, FALSE, FALSE),

('Anime Skull Throne Figure',         1, 'Anime Dark Throne Collectible Figure | Premium Anime Statue',                        'A striking anime figure seated on a skull-adorned throne. Impressive gothic-style detailing and craftsmanship make this a standout collector piece.',                      'Material: Cold-cast Resin | Height: ~25 cm | Throne: Skull-and-bone carved gothic throne sculpt | Paint: Dark wash with silver dry-brush highlights | Eyes: Hand-painted glowing effect | Weight: ~520 g | Collector packaging',           'Anime collectors, premium displays',            2799.00, 4399.00, 36, 4.8, 150,  'images/products/anime/16.jpg', 10, TRUE,  FALSE, TRUE,  TRUE),

('Anime Dual Sword Warrior Statue',   1, 'Anime Dual Sword Action Figure | Dynamic Battle Pose Statue',                        'A highly dynamic statue featuring an anime warrior mid-attack with dual swords and motion blur effects, capturing the peak moment of battle.',                             'Material: Resin body + PVC motion-effect parts | Height: ~23 cm | Swords: Separately attached crossed-blade sculpt | Base: Dynamic cracked-ground scenic base | Paint: Battle-worn weathered finish | Weight: ~490 g',                    'Anime figure collectors',                       2399.00, 3999.00, 40, 4.7, 140,  'images/products/anime/17.jpg', 14, FALSE, FALSE, FALSE, FALSE),

('Anime Scout Warrior Figure',        1, 'Anime Scout Warrior Battle Figure | Collectible Anime Statue',                       'Detailed anime warrior figure in a mid-combat scouting pose. Action effects and flowing cloak with intricate sculpting on every armor plate.',                            'Material: Resin/PVC blended composite | Height: ~23 cm | Cloak: Flexible dynamic PVC | Armor: Multi-piece layered sculpt | Base: Dusty terrain scenic display base | Paint: Realistic battle-worn tones | Weight: ~460 g',               'Anime collectors, display setups',              2399.00, 3899.00, 38, 4.7, 135,  'images/products/anime/18.jpg', 14, FALSE, FALSE, FALSE, FALSE),

('Anime Duo Character Figure',        1, 'Anime Duo Character Collectible Figures | Anime Display Set',                        'A stylish figure set featuring two anime characters side by side. One taller hero pose and one shorter companion, perfect for shelf displays.',                            'Material: PVC plastic | Height: ~18 cm each | Paint: Clean cel-shaded color finish | Base: Shared scenic display base | Characters: 2 fully painted figures | Detail: Outfit and hair strand-level sculpting | Weight: ~300 g total',      'Collectors, anime fans',                        1399.00, 2299.00, 39, 4.6, 260,  'images/products/anime/19.jpg', 22, FALSE, FALSE, TRUE,  TRUE),

('Anime Mini Character Display Set',  1, 'Anime Mini Figure Shelf Display | Cute Anime Collectibles',                          'A cute set of mini anime figures designed to decorate shelves, desks, or manga collections. Affordable entry into anime figure collecting.',                               'Material: PVC plastic | Height: ~7 cm each | Paint: Bright vibrant color coat | Base: Individual round flat base per figure | Pack: Set of 5 characters | Detail: Chibi-scale outfit detailing | Weight: ~20 g each',                      'Anime fans, collectors',                        799.00,  1299.00, 38, 4.6, 320,  'images/products/anime/20.jpg', 30, FALSE, FALSE, FALSE, FALSE),

('Anime Cute Chibi Figure Set',       1, 'Anime Chibi Character Figure Set | Kawaii Desk Decor',                                'Adorable chibi-style anime figures with vibrant colors and oversized cute expressions. Perfect for desk decoration and as a starter anime collection.',                    'Material: Soft PVC | Height: ~6-7 cm each | Style: Super-deformed chibi proportions | Paint: High-gloss vibrant colors | Base: Flat round individual base | Pack: Set of 6 chibi figures | Expression: Smile + big sparkle eyes | Weight: ~20 g each', 'Anime fans, desk decor',              699.00,  1099.00, 36, 4.5, 410,  'images/products/anime/21.jpg', 34, TRUE,  FALSE, FALSE, TRUE);


-- ============================================================
-- SECTION 3: KPOP PRODUCTS  (category_id = 6)
-- Images: images/products/kpop/1.jpg to 26.jpg
-- Total : 26 products
-- ============================================================

INSERT INTO products (product_name, category_id, key_words, description, specifications, ideal_for, price, mrp, discount, rating, reviews, image_link, stock, is_new, is_popular, is_recommended, show_on_home) VALUES

('BTS Engraved Artist Edition Bracelet',      6, 'BTS Premium Engraved Stainless Steel Bracelet | K-Pop Fan Merchandise',          'Sleek engraved BTS bracelet combining minimalist fandom aesthetics with durable stainless steel. Perfect for daily wear, fan events, or gifting.',                         'Material: 316L Premium Stainless Steel | Finish: Mirror-polished with engraved band design | Size: Adjustable open cuff, fits wrist 15-20 cm | Width: 8 mm | Weight: ~120 g | Anti-tarnish coating | Packaging: Velvet gift box',              'BTS fans, ARMY collectors, daily fashion wear', 799.00,  1299.00, 38, 4.6, 820,  'images/products/kpop/1.jpg',  49, TRUE,  TRUE,  FALSE, TRUE),

('BTS LED Light Wristband',                   6, 'BTS LED Glow Wristband | K-Pop Concert Accessory | Rechargeable Light Band',     'Vibrant LED lighting wristband inspired by BTS concerts. Adds glowing fandom energy to concerts, fan meets, or casual wear.',                                             'Material: Soft silicone outer band | LED Strip: Multicolor RGB embedded LEDs | Power: Built-in rechargeable 80 mAh battery | Charge: Micro-USB, 1.5 hr full charge | Battery life: ~6 hours | Modes: 3 light patterns | Size: Adjustable',  'BTS concerts, fan events, night parties',       699.00,  1099.00, 36, 4.5, 640,  'images/products/kpop/2.jpg',  45, FALSE, TRUE,  FALSE, TRUE),

('Stray Kids SKZ Necklace',                   6, 'SKZ Engraved Pendant Necklace | K-Pop Jewelry | Stainless Steel Chain',          'Stylish SKZ engraved pendant for Stray Kids fans who love subtle meaningful accessories. Polished finish and durable chain for everyday wear.',                            'Material: 316L Stainless Steel chain + pendant | Pendant Size: 2 x 2 cm | Chain Length: ~50 cm with extender | Engraving: Laser-precision SKZ logo | Finish: Polished mirror silver | Clasp: Standard lobster clasp | Weight: ~80 g',       'Stray Kids fans, K-Pop jewelry collectors',     899.00,  1399.00, 36, 4.7, 720,  'images/products/kpop/3.jpg',  34, FALSE, FALSE, TRUE,  TRUE),

('SKZOO Character Plush Set',                 6, 'Stray Kids SKZOO Official Mini Plush Collection | OT8 Set',                      'Complete SKZOO set featuring all 8 Stray Kids animal counterparts. Embroidered details and soft polyester fill for display or cuddle.',                                   'Material: Ultra-soft polyester outer + PP cotton fill | Height: ~15 cm each | Pack: Full OT8 set (8 plushies) | Detail: Embroidered eyes, nose, and outfit | Surface: Machine washable | Packaging: Individual tags per character',           'OT8 Stay collectors, shelf decor, fan meetups', 1899.00, 2499.00, 24, 4.8, 1150, 'images/products/kpop/4.jpg',  78, TRUE,  TRUE,  TRUE,  TRUE),

('Stray Kids SKZ University Stationery Kit',  6, 'SKZ-SKZOO University Spiral Notebook & Pen Set',                                 'University themed stationery set featuring SKZOO characters in collegiate outfits. Makes everyday note-taking a fan experience.',                                         'Notebook: A5 spiral-bound, 120 ruled pages, 80 GSM paper | Cover: 350 GSM matte hardback with SKZOO varsity print | Pen: 0.5 mm smooth black gel ink + SKZOO character clip | Bookmark ribbon | Weight: ~280 g',                          'School notes, bullet journaling, Stays',        3499.00, 4999.00, 30, 4.8, 670,  'images/products/kpop/5.jpg',  56, FALSE, FALSE, FALSE, FALSE),

('BTS TinyTAN Dynamite Figure Set',           6, 'BTS TinyTAN Dynamite Edition Mini Figures | Set of 7',                           'Highly detailed mini-figures of all 7 BTS members in iconic Dynamite music video retro outfits with detachable circular display stands.',                                 'Material: Premium PVC | Height: ~7.5 cm per figure | Pack: 7 figures (RM, Jin, SUGA, j-hope, Jimin, V, Jungkook) | Base: Detachable circular display stand per figure | Paint: Multi-layer cel-shaded color coat | Weight: ~50 g each',    'BTS ARMY collectors, desktop decoration',       3499.00, 4999.00, 30, 4.9, 5400, 'images/products/kpop/6.jpg',  45, TRUE,  TRUE,  TRUE,  TRUE),

('Stray Kids Maxident Album Box',              6, 'Stray Kids MAXIDENT Limited Edition Box Set',                                    'Comprehensive Maxident album package with CD, large-scale photobooks, photocards, poster, and sticker pack in a pink Heart aesthetic box.',                               'Contents: 1 CD-R + 80-page photobook + lyric paper + 2 random photocards | Bonus: Folded A2 poster + sticker sheet | Box: Premium thick cardboard with matte spot-UV finish | Dimensions: ~16 x 16 x 2 cm | Weight: ~350 g',              'Stray Kids collectors, shelf display',          2299.00, 3200.00, 28, 4.8, 3100, 'images/products/kpop/7.jpg',  89, FALSE, FALSE, FALSE, FALSE),

('BTS Proof Anthology Album',                 6, 'BTS - Proof Standard Edition 3-CD Box Set',                                      'Ultimate BTS anthology across 3 CDs covering their entire career with 48 tracks, 4 photobooks, and a photocard set in a premium hardcase.',                               'Contents: 3 CDs + 4 photobooks (The Art of Proof series) + 1 random photocard set | Dimensions: ~190 x 252 x 35 mm | Box: Premium heavyweight hardcase | Tracklist: 48 tracks | Weight: ~900 g | Shrink-wrapped',                          'ARMY collectors, K-Pop gifting',                3499.00, 4999.00, 30, 4.9, 5400, 'images/products/kpop/8.jpg',  98, FALSE, TRUE,  FALSE, TRUE),

('SKZOO Character Hoodie Wolf Chan Edition',  6, 'Stray Kids SKZOO Embroidered Oversized Hoodie | Wolf Chan Bang Chan',            'Premium black oversized hoodie with high-quality embroidered Wolf Chan on chest and screen-printed SKZ logo on sleeve. Heavy fleece cotton for comfort.',                  'Material: 80% Cotton + 20% Polyester fleece | Weight: 380 GSM heavyweight | Embroidery: Wolf Chan chest + SKZ sleeve logo | Fit: Relaxed unisex oversized | Pocket: Front kangaroo | Hood: Adjustable drawstring | Sizes: S-XXL',          'DominATE Tour outfits, Bang Chan fans',         2299.00, 3200.00, 28, 4.8, 3100, 'images/products/kpop/9.jpg',  67, FALSE, FALSE, TRUE,  TRUE),

('BTS L Atelier des Subtils Perfume Set',     6, 'VT x BTS Official L Atelier Perfume | Member-Inspired Fragrances',              'Fragrances inspired by BTS member personalities, created with French master perfumer Frederic Burtin. Available in 7 member-themed scents.',                               'Type: Eau de Parfum | Volume: 50 ml per bottle | Scents: Coton (Jin), Poudre, Vert, Bois, Ocean (JK), Musk, Citrus | Bottle: Minimalist glass with member photo card | Origin: Made in France / Produced in Korea | Weight: ~200 g',       'ARMY fragrance lovers, luxury K-Pop gifting',   5999.00, 8500.00, 29, 5.0, 12000, 'images/products/kpop/10.jpg', 90, TRUE,  TRUE,  TRUE,  TRUE),

('BTS Member Name Bar Bracelet',              6, 'BTS Official Inspired Leather & Metal Bar Bracelet | Laser Engraved',            'Sophisticated stainless steel bar bracelet laser-engraved with your chosen BTS member name. Adjustable vegan leather band for any wrist size.',                           'Material: High-polished 316L Stainless Steel bar + Vegan leather band | Bar Size: 3 x 0.8 cm | Engraving: Member name (RM/Jin/SUGA/j-hope/Jimin/V/JK) | Closure: Adjustable buckle | Anti-tarnish: Yes | Gift packaging: Included',        'Minimalist ARMY, bias name jewelry collectors',  3499.00, 4999.00, 30, 4.9, 5400, 'images/products/kpop/11.jpg', 90, FALSE, FALSE, FALSE, FALSE),

('Jin The Astronaut Album Set Ver 1 and 2',   6, 'Jin BTS - The Astronaut Solo Single Album | 2-Version Bundle',                   'Both versions (Purple + Green) of Jin solo debut co-written with Coldplay. Includes 2 CDs, 2 photobooks, lyric cards, postcards, and stickers.',                          'Contents: 2 CDs (Ver.1 Purple + Ver.2 Green) | Photobooks: 2 x 84-page books | Extras: Lyric Cards + Postcards + Sticker sheets | Photocards: 2 random out of 4 | Theme: Interstellar outer space | Weight: ~500 g',                      'Jin solo collectors, Coldplay x BTS fans',      2299.00, 3200.00, 28, 4.8, 3100, 'images/products/kpop/12.jpg', 56, FALSE, FALSE, FALSE, FALSE),

('Jungkook GOLDEN 3-Version Album Set',       6, 'Jungkook Solo Album GOLDEN | SHINE SOLID SUBSTANCE Set',                         'All 3 versions of Jungkook historic solo album GOLDEN capturing his global pop star debut. Each version includes CD, photobook, postcards, stickers, and photocards.',     'Versions: Shine (Green) + Solid (White) + Substance (Blue) | Per album: 1 CD + 64-page photobook + postcards + symbol stickers + 1 photocard | Box: Premium hardcase per version | Total weight: ~900 g',                                 'Jungkook collectors, GOLDEN era fans',          5999.00, 8500.00, 29, 5.0, 12000, 'images/products/kpop/13.jpg', 78, TRUE,  TRUE,  FALSE, TRUE),

('TXT The Dream Chapter STAR Debut Album',    6, 'TOMORROW X TOGETHER TXT - The Dream Chapter STAR 1st Mini Album',                'TXT debut mini-album introducing their unique youth and friendship narrative. Features iconic tracks CROWN, Cat & Dog, and Blue Orangeade.',                               'Contents: 1 CD + 80-page photobook + 2 random photocards (Ver.1 & 2) + 1 transparent photocard + 2 sticker sheets | Tracklist: 5 tracks | Dimensions: 148 x 185 x 7 mm | Weight: ~450 g',                                               'New MOAs, TXT debut collectors',                3499.00, 4999.00, 30, 4.9, 5400, 'images/products/kpop/14.jpg', 23, FALSE, FALSE, FALSE, FALSE),

('Agust D D-DAY World Tour Tumbler',          6, 'Official SUGA Agust D TOUR D-DAY THE FINAL Insulated Tumbler',                   'High-performance insulated tumbler commemorating SUGA Agust D D-DAY World Tour with the signature brutalist logo on a sleek matte black finish.',                        'Material: Double-walled 304 Stainless Steel | Capacity: 400 ml | Insulation: Keeps hot 6 hrs, cold 12 hrs | Lid: Spill-proof screw cap | Base: Anti-skid silicone ring | Finish: Matte black with tour logo | Care: Hand wash only',       'ARMY touring fans, daily use merchandise',      2299.00, 3200.00, 28, 4.8, 3100, 'images/products/kpop/15.jpg', 56, FALSE, FALSE, TRUE,  FALSE),

('Mentally Dating Jungkook Coffee Mug',       6, 'BTS Jungkook Fan-Meme Ceramic Mug | 330 ml',                                     'Humorous white ceramic mug with the fan-favorite phrase Mentally Dating Jungkook in bold typography. Double-sided print with microwave and dishwasher safe ceramic.',      'Material: High-quality gloss ceramic | Capacity: 330 ml | Print: Double-sided wrap-around high-definition design | Handle: Ergonomic C-handle | Care: Microwave safe + dishwasher safe | Dimensions: ~9 x 8 cm | Weight: ~300 g',           'JK biases, K-Pop office gifts, fan mugs',       5999.00, 8500.00, 29, 5.0, 12000, 'images/products/kpop/16.jpg', 56, FALSE, TRUE,  FALSE, TRUE),

('Stray Kids OT8 Names Graphic Hoodie',       6, 'Stray Kids Member Signature List Hoodie | Black Streetwear',                     'Sleek black hoodie listing all 8 Stray Kids member names in clean minimalist white typography. Bio-washed cotton for a soft premium feel.',                                'Material: 100% Premium Bio-washed Cotton | Weight: 260 GSM | Print: White screen-printed member name list on front | Fit: Unisex regular fit | Color: Deep jet black | Sizes: S-XXL | Care: Machine wash cold inside out',                 'Stays, DominATE Tour outfits, K-Pop streetwear', 3499.00, 4999.00, 30, 4.9, 5400, 'images/products/kpop/17.jpg', 76, FALSE, FALSE, FALSE, FALSE),

('Can t Hear You K-Pop Slogan Tee',           6, 'Can t Hear You I m Listening To K-Pop Graphic T-Shirt',                          'Relatable K-Pop slogan tee with a minimalist headphone illustration. A fun everyday tee for K-Pop stans who live in their own fandom world.',                              'Material: Soft ring-spun 100% Cotton | Weight: 180 GSM | Print: Chest graphic with slogan + headphone illustration | Neckline: Classic crew neck | Fit: Unisex regular | Sizes: XS-XXL | Care: Machine wash cold, tumble dry low',         'K-Pop stans, concert wear, casual streetwear',  2299.00, 3200.00, 28, 4.8, 3100, 'images/products/kpop/18.jpg', 90, FALSE, FALSE, TRUE,  TRUE),

('Custom ARMY Hand-Painted Denim Jacket',     6, 'Bespoke BTS ARMY Fan-Art Denim Jacket | One-of-a-Kind Wearable Art',            'Premium denim jacket with a large hand-painted BTS ARMY tribute on the back featuring Love Yourself floral motifs. Each jacket is uniquely textured.',                    'Material: Heavyweight distressed denim ~12 oz | Paint: Water-resistant textile paints + protective sealant | Design: Custom ARMY typography with galaxy or floral accents | Hardware: Reinforced metal buttons | Size: One size oversized fit', 'BTS concerts, high-end K-Pop fashion collectors', 5999.00, 8500.00, 29, 5.0, 12000, 'images/products/kpop/19.jpg', 45, TRUE, FALSE, FALSE, FALSE),

('BTS ARIRANG World Tour Official Tee',       6, 'BTS 2026 World Tour ARIRANG Official Commemorative T-Shirt',                     'Official Arirang World Tour 2026 shirt celebrating BTS reunion. Front features Three Red Circles logo, back has the full 82-show world tour itinerary.',                  'Material: 100% Premium Heavyweight Cotton 240 GSM | Front: Three Red Circles symbolic logo print | Back: Full world tour dates list | Neckline: Crew neck | Sizes: S-XXL | Care: Machine wash cold | Weight: ~220 g per shirt',            'Arirang comeback fans, BTS collectors',         2690.00, 3800.00, 29, 5.0, 5400, 'images/products/kpop/20.jpg', 67, TRUE,  TRUE,  TRUE,  TRUE),

('BLACKPINK Member Est Chibi Sweatshirt',     6, 'BLACKPINK Member Chibi Edition Sweatshirt | Lisa Jisoo Jennie Rose',            'Ultra-soft crewneck sweatshirts featuring each BLACKPINK member name in varsity-style lettering with a hand-drawn chibi illustration of the member.',                     'Material: 100% Premium Fleece Cotton 320 GSM | Designs: Lisa-Brown, Jisoo-Light Blue, Jennie-Beige, Rose-Pink | Art: Chibi member illustration + name + birth year | Fit: Relaxed unisex | Sizes: S-XXL | Care: Cold wash gentle cycle',  'Blinks, cozy concert outfits, group matching',  5999.00, 8500.00, 29, 5.0, 12000, 'images/products/kpop/21.jpg', 88, FALSE, TRUE,  TRUE,  TRUE),

('Enhypen Member Acrylic Keychain Set',       6, 'Enhypen K-Pop Member Acrylic Keychains | Idol Name & Photo Charm',              'Colorful acrylic keychains featuring Enhypen member names and mini photo charms with glossy finish. Fun fandom accessory for bags and keys.',                              'Material: 4 mm premium acrylic + metal keyring | Design: Member name tag + mini photo charm combo | Finish: Gloss UV print both sides | Size: ~6 x 3 cm | Weight: ~40 g per keychain | Pack: Sold individually or as a set',              'Enhypen fans, bag accessories, K-Pop gifts',    269.00,  380.00,  29, 5.0, 5400, 'images/products/kpop/22.jpg', 23, FALSE, FALSE, FALSE, FALSE),

('Jungwon K-Pop Graphic T-Shirt',             6, 'Jungwon Inspired K-Pop Graphic T-Shirt | Aesthetic Idol Eye Print',             'Stylish black graphic tee with an intense aesthetic eye print inspired by Jungwon iconic stage visuals. Subtle yet powerful K-Pop fashion for everyday wear.',             'Material: 100% Combed Cotton | Weight: 190 GSM | Print: High-definition eye graphic on chest | Fit: Regular unisex fit | Color: Jet black base | Neckline: Crew neck | Sizes: XS-XXL | Care: Machine wash cold inside out',               'K-Pop fans, idol-aesthetic streetwear lovers',  3499.00, 4999.00, 30, 4.9, 3100, 'images/products/kpop/23.jpg', 78, FALSE, FALSE, FALSE, TRUE),

('BLACKPINK Character Acrylic Carabiner Keyring', 6, 'BLACKPINK Character Acrylic Carabiner Keyring | Heart Clip Idol Charm',      'Cute BLACKPINK character carabiner keyring with adorable mascot charm and a heart-shaped metal carabiner clip. Perfect for bags, keys, or fan collections.',              'Material: 3 mm durable acrylic charm + zinc alloy heart carabiner | Charm: BLACKPINK character mascot illustration | Finish: Smooth glossy surface | Total Length: ~9 cm | Carabiner: Functional clip opening | Weight: ~50 g',           'BLACKPINK fans, bag accessories, collectors',   2299.00, 3200.00, 28, 4.8, 3100, 'images/products/kpop/24.jpg', 45, FALSE, FALSE, FALSE, FALSE),

('BTS Proof Photocard Binder Set',            6, 'BTS ARMY Photocard Collection Binder | Premium K-Pop Card Display',             'Premium binder designed for BTS photocard collections with member-sorted sections, acid-free protective sleeves, and a Proof anthology inspired PU leather cover.',        'Cover: PU leather with Proof-era design | Sleeves: 60 acid-free clear pockets (120 card capacity) | Sections: 7 member-sorted dividers + bonus section | Size: A5 compact format | Ring: D-ring binder | Weight: ~320 g',                'ARMY photocard collectors, K-Pop organizers',   1299.00, 1999.00, 35, 4.7, 890,  'images/products/kpop/25.jpg', 65, FALSE, FALSE, TRUE,  FALSE),

('Stray Kids Felix Acrylic Stand',            6, 'Stray Kids Felix Acrylic Character Stand | K-Pop Desk Decor',                   'Beautifully printed acrylic standing figure of Felix from Stray Kids. High-resolution character print on clear acrylic with a sturdy weighted base for desk display.',    'Material: 5 mm premium crystal-clear acrylic | Print: High-resolution Felix character artwork | Base: Weighted black acrylic slot-in base | Height: ~18 cm | Base Dimensions: 8 x 5 cm | Finish: Gloss UV print | Weight: ~120 g',         'Felix biases, Stray Kids fans, desk decor',     899.00,  1399.00, 36, 4.6, 540,  'images/products/kpop/26.jpg', 48, FALSE, FALSE, FALSE, TRUE);




-- ============================================================
-- SECTION 4: POP PRODUCTS  (category_id = 7)
-- Images: images/products/pop/1.jpg to 20.jpg
-- Total : 20 products
-- ============================================================
INSERT INTO products (product_name, category_id, key_words, description, specifications, ideal_for, price, mrp, discount, rating, reviews, image_link, stock, is_new, is_popular, is_recommended, show_on_home) VALUES

('Taylor Swift Eras Tour Poster Set',         7, 'Taylor Swift Eras Tour Decorative Poster | Pop Music Wall Art | Swiftie Room Decor',              'A stunning set of four high-quality art prints celebrating every Taylor Swift era from Taylor Swift to Midnights. Each poster features era-specific color palettes and iconic lyrics, perfect for Swiftie walls.',                                        'Contents: 4 posters | Paper: 220 GSM matte coated | Size: A3 (29.7 x 42 cm) each | Print: UV fade-resistant ink | Finish: Matte anti-glare surface | Packaging: Rolled in protective tube | Weight: ~180 g',                                         'Swifties, pop fans, room decor, gifting',                    799.00,  1299.00, 38, 4.8, 1240, 'images/products/pop/1.jpg',  60, TRUE,  TRUE,  TRUE,  TRUE),

('Taylor Swift TTPD Vinyl Record',            7, 'Taylor Swift The Tortured Poets Department Vinyl LP | Collector Edition',                         'Collectible vinyl LP of Taylor Swift The Tortured Poets Department with an exclusive ghost-white pressing and lyric insert. A premium piece for Swiftie collectors and vinyl enthusiasts.',                                                            'Format: 12-inch LP Vinyl | Pressing: Ghost white colored vinyl | RPM: 33⅓ | Tracklist: 31 tracks (standard version) | Insert: Full lyric booklet | Sleeve: Heavyweight matte gatefold sleeve | Weight: ~300 g | Packaging: Shrink wrapped',          'Swifties, vinyl collectors, pop music fans',                 3499.00, 4999.00, 30, 4.9, 980,  'images/products/pop/2.jpg',  40, TRUE,  TRUE,  TRUE,  TRUE),

('Billie Eilish Hit Me Hard Soft Vinyl LP',   7, 'Billie Eilish HIT ME HARD AND SOFT Vinyl Record | Exclusive Color Pressing',                   'Exclusive colored vinyl pressing of Billie Eilish third studio album HIT ME HARD AND SOFT. Bold blue pressing with inner sleeve artwork and digital download card.',                                                                                  'Format: 12-inch LP Vinyl | Pressing: Exclusive blue vinyl | RPM: 33⅓ | Tracklist: 10 tracks | Inner Sleeve: Full artwork inner sleeve | Insert: Lyric + digital download card | Sleeve: Matte embossed outer sleeve | Weight: ~280 g',               'Billie Eilish fans, vinyl collectors',                       2999.00, 4299.00, 30, 4.8, 670,  'images/products/pop/3.jpg',  35, FALSE, TRUE,  FALSE, TRUE),

('Pop Idol Acrylic Standee Collection',       7, 'Pop Artist Acrylic Photo Standee | Idol Desk Decor | Fan Collection',                           'Set of vibrant full-color acrylic standees of your favorite pop artists. High-resolution photo printing on premium crystal acrylic with weighted display bases.',                                                                                       'Material: 5 mm crystal-clear acrylic | Print: High-resolution character artwork, gloss UV coated | Base: Weighted black acrylic slot-in base per piece | Height: ~18 cm per standee | Pack: 4 standees | Weight: ~100 g each',                       'Pop fans, idol collectors, desk decor',                      1499.00, 2299.00, 35, 4.7, 520,  'images/products/pop/4.jpg',  45, FALSE, FALSE, TRUE,  TRUE),

('Pop Music LED Neon Sign Lamp',              7, 'Music Note Neon LED Sign | Pop Music Room Decor Light | Wall Glow Lamp',                       'Eye-catching neon LED sign shaped as music notes and a treble clef. Creates a warm pink-purple ambient glow perfect for music rooms, studios, or bedroom walls. USB powered with dimmer.',                                                              'Material: Flexible LED neon tube + acrylic backing | Design: Music note + treble clef silhouette | Colors: Pink + purple neon glow | Power: USB 5V | Dimensions: ~35 x 25 cm | Brightness: 3-level dimmable | Mount: Freestanding or wall hang',      'Music lovers, room decor, pop fans',                         1599.00, 2499.00, 36, 4.7, 480,  'images/products/pop/5.jpg',  50, TRUE,  TRUE,  FALSE, TRUE),

('Swiftie Era Friendship Bracelet Set',       7, 'Taylor Swift Eras Tour Friendship Bracelet Kit | Swiftie Fan Accessory | Beaded Bracelets',    'The ultimate Swiftie friendship bracelet making kit inspired by the viral Eras Tour bracelet-trading tradition. Includes letter beads, charm beads, and elastic cord to make 15+ bracelets.',                                                          'Contents: 500+ mixed letter beads + 200 charm beads + 10 m elastic cord + 2 needles | Charm styles: Music notes, stars, hearts, guitar, cats | Bead size: 6 mm | Storage: Ziplock sorting bags | Instructions: Included | Weight: ~220 g',            'Swifties, DIY craft lovers, fan meetups',                    699.00,  1199.00, 42, 4.8, 1680, 'images/products/pop/6.jpg',  80, FALSE, TRUE,  TRUE,  TRUE),

('Pop Artist Photo Card Binder',              7, 'Pop Idol Photocard Collection Binder | A5 Fan Card Display Album | Premium PU Cover',          'Premium A5 binder designed for collecting pop artist photocards, polaroids, and fan cards. Acid-free sleeves protect cards while the durable PU cover keeps everything organized and stylish.',                                                        'Cover: PU leather printed with music motif | Sleeves: 60 acid-free clear pockets (120 card capacity) | Sections: 6 artist-sorted dividers | Size: A5 compact | Ring: D-ring binder mechanism | Weight: ~310 g',                                    'Pop fans, photocard collectors, fan organizers',             999.00,  1599.00, 37, 4.7, 630,  'images/products/pop/7.jpg',  65, FALSE, FALSE, FALSE, FALSE),

('Ariana Grande Thank U Next Mug',            7, 'Ariana Grande Thank U Next Ceramic Coffee Mug | Pop Quote Fan Mug | 330 ml',                   'Glossy white ceramic mug printed with the iconic Thank U Next logo and signature Ariana Grande typography. Double-sided design with the album cover inspired pastel aesthetic.',                                                                         'Material: High-grade gloss ceramic | Capacity: 330 ml | Print: Double-sided wrap-around high-resolution design | Handle: Ergonomic C-handle | Care: Microwave safe + dishwasher safe | Dimensions: ~9 x 8 cm | Weight: ~300 g',                      'Ariana fans, pop music lovers, gift mugs',                   499.00,  899.00,  44, 4.6, 410,  'images/products/pop/8.jpg',  70, FALSE, FALSE, FALSE, TRUE),

('Music Lover Canvas Tote Bag',               7, 'Music Lover Graphic Canvas Tote Bag | Pop Fan Shopping Bag | Aesthetic Carry Bag',             'Spacious natural canvas tote with a bold music-lover graphic design. Features a vintage record player illustration with the phrase Music Is Life in retro typography.',                                                                               'Material: 12 oz natural canvas | Size: 38 x 42 cm | Handles: 60 cm cotton rope handles | Print: Screen-printed front graphic | Capacity: ~10 liters | Inner lining: None (open style) | Care: Machine washable cold | Weight: ~200 g',              'Music fans, students, daily carry, eco users',               449.00,  799.00,  44, 4.5, 380,  'images/products/pop/9.jpg',  90, FALSE, FALSE, FALSE, FALSE),

('Pop Icon Enamel Pin Set',                   7, 'Pop Culture Enamel Pin Collection | Music Icon Badge Set | Fandom Accessory',                  'Set of six hard enamel pins inspired by iconic pop culture symbols: microphone, vinyl disc, cassette, music note, headphones, and a star. Perfect for jackets, bags, and pin boards.',                                                               'Material: Hard enamel + polished gold metal base | Size: 2.5–3.5 cm per pin | Finish: Smooth enamel + rubber backing clutch | Pack: 6 pins in velvet display card | Weight: ~10 g per pin | Packaging: Printed backing card',                      'Pop fans, pin collectors, fashion accessories',              549.00,  999.00,  45, 4.6, 295,  'images/products/pop/10.jpg', 100, FALSE, FALSE, FALSE, TRUE),

('Dua Lipa Future Nostalgia Hoodie',          7, 'Dua Lipa Future Nostalgia Graphic Hoodie | Pop Disco Streetwear | Fan Apparel',                'Retro-inspired hoodie featuring bold Future Nostalgia typography with a disco era color palette of gold and burgundy. Heavyweight cotton fleece for premium comfort.',                                                                                  'Material: 80% Cotton + 20% Polyester fleece | Weight: 380 GSM heavyweight | Print: Oversized chest graphic in retro gold typography | Fit: Slightly oversized unisex | Pocket: Front kangaroo | Hood: Adjustable drawstring | Sizes: S-XXL',        'Dua Lipa fans, retro pop lovers, casual fashion',            1699.00, 2699.00, 37, 4.7, 320,  'images/products/pop/11.jpg', 55, FALSE, TRUE,  FALSE, TRUE),

('Headphones Aesthetic Desk Lamp',            7, 'Headphone Silhouette LED Acrylic Lamp | Music Room Desk Decor | Pop Fan Night Light',         'Acrylic LED lamp featuring a detailed headphones silhouette with edge-lit warm glow. A clean minimal design that suits any music fan bedroom, studio, or workstation.',                                                                               'Material: Premium 6 mm acrylic panel + ABS base | Silhouette: Headphones icon edge-lit | Light: Warm white 3000K | Power: USB 5V | Height: ~20 cm | Switch: Slide on/off on base | Cord: 1.2 m USB | Weight: ~280 g',                              'Music fans, room decor, pop enthusiasts',                    899.00,  1499.00, 40, 4.6, 340,  'images/products/pop/12.jpg', 60, FALSE, FALSE, FALSE, FALSE),

('Pop Star Idol Cushion Cover',               7, 'Pop Idol Graphic Cushion Cover | Music Fan Pillow Case | Home Decor',                          'Soft polyester cushion cover featuring vibrant pop idol graphics in bold color blocks. Brings a music-room vibe to sofas, beds, and lounge corners. Available in multiple designs.',                                                                   'Material: 100% Polyester microfiber | Size: 40 x 40 cm | Print: All-over sublimation with idol artwork | Closure: Concealed zip with anti-slip slider | Thread count: 200TC | Care: Machine washable cold | Weight: ~120 g',                       'Pop fans, home decor, bedrooms, gifting',                    349.00,  699.00,  50, 4.5, 290,  'images/products/pop/13.jpg', 75, FALSE, FALSE, FALSE, FALSE),

('Vinyl Record Wall Clock',                   7, 'Vintage Vinyl Record Wall Clock | Music Room Decor | Pop Culture Home Accessory',              'Functional wall clock designed to look exactly like a classic vinyl record. Silent quartz movement, glossy black finish with gold track detailing, and a retro label center.',                                                                         'Material: Lightweight MDF + acrylic face | Diameter: 30 cm | Movement: Silent quartz (AAA battery, not included) | Finish: Gloss black with gold track lines | Center: Retro label design | Mount: Single hook wall hang | Weight: ~280 g',       'Music lovers, home decor, pop culture fans',                 799.00,  1299.00, 38, 4.6, 410,  'images/products/pop/14.jpg', 55, FALSE, TRUE,  TRUE,  TRUE),

('Cassette Tape Retro Keychain',              7, 'Retro Cassette Tape Keychain | 80s Pop Culture Accessory | Fun Novelty Keyring',               'Chunky miniature cassette tape keychain in retro pastel colors. A nostalgic nod to 80s pop music that clips onto bags, keys, or backpack zippers with a durable metal ring.',                                                                          'Material: Hard ABS plastic + metal split ring | Size: ~5 x 3 cm | Finish: Painted matte surface | Detail: Functional realistic cassette design with spool detail | Ring diameter: 2.5 cm | Weight: ~18 g | Colors: Multiple pastel options',       'Retro music fans, pop culture lovers, collectors',           299.00,  599.00,  50, 4.5, 360,  'images/products/pop/15.jpg', 120, FALSE, FALSE, FALSE, FALSE),

('Taylor Swift Midnights Acrylic Standee',    7, 'Taylor Swift Midnights Era Acrylic Standee | Swiftie Desk Decor | Crystal Photo Display',     'Premium crystal acrylic standee with a high-resolution Midnights-era photo print. The deep blue tones and star-glitter design make it an elegant display piece for any Swiftie desk or shelf.',                                                         'Material: 5 mm crystal-clear acrylic | Print: Midnights era high-resolution photo, glossy UV coated | Base: Weighted slot-in black acrylic base | Height: ~20 cm | Base Dimensions: 10 x 5 cm | Finish: Gloss UV print | Weight: ~130 g',          'Swifties, Midnights era fans, desk decor',                   1099.00, 1799.00, 39, 4.8, 560,  'images/products/pop/16.jpg', 48, TRUE,  TRUE,  FALSE, TRUE),

('Wireless Pop Beats Mini Speaker',           7, 'Portable Bluetooth Mini Speaker | Pop Music Fan Design | Wireless Speaker Gift',               'Compact Bluetooth speaker with a retro vinyl-record inspired design. Powerful 5W output, 8-hour battery life, and a colorful pop-art finish. Perfect for music lovers on the go.',                                                                     'Driver: 5W full-range speaker | Bluetooth: 5.0, range 10 m | Battery: 1200 mAh, 8-hour playback | Charge: USB-C, 2-hour full charge | Dimensions: 8 cm diameter | Water resistance: IPX4 splash-proof | Colors: Multiple options | Weight: ~180 g', 'Music fans, gifting, casual use, pop lovers',               1899.00, 2999.00, 37, 4.7, 280,  'images/products/pop/17.jpg', 40, TRUE,  FALSE, TRUE,  TRUE),

('Music Festival Fan Fanny Pack',             7, 'Pop Concert Fanny Pack | Festival Fan Bag | Aesthetic Bum Bag',                                'Stylish crossbody fanny pack designed for music festivals and pop concerts. Bold neon pop-art print with multiple secure compartments to carry essentials hands-free.',                                                                               'Material: Water-resistant 600D polyester | Dimensions: 28 x 14 x 6 cm | Compartments: 1 main zip + 2 front zips | Strap: Adjustable nylon webbing, max 120 cm | Closure: Metal zip sliders | Print: Front pop-art music graphic | Weight: ~250 g',  'Concert goers, festival fans, daily casual',                 699.00,  1199.00, 42, 4.5, 230,  'images/products/pop/18.jpg', 70, FALSE, FALSE, FALSE, TRUE),

('Superstar Pop Graffiti Tote Backpack',      7, 'Pop Culture Graffiti Graphic Backpack | Fan Streetwear Bag | College Bag',                    'Eye-catching backpack with a bold pop-culture graffiti design featuring music icons and neon splatter art. Padded laptop compartment and multiple pockets for practical everyday use.',                                                              'Material: 600D Oxford polyester | Dimensions: 44 x 30 x 15 cm | Capacity: ~25 liters | Laptop sleeve: Fits up to 15-inch | Compartments: 1 main + 1 front + 2 side bottle pockets | Straps: Padded adjustable | Print: Front graffiti graphic | Weight: ~550 g', 'Students, pop fans, casual everyday use',            1299.00, 1999.00, 35, 4.6, 310,  'images/products/pop/19.jpg', 45, FALSE, FALSE, FALSE, FALSE),

('Pop Superstar Trophy Desk Figure',          7, 'Music Superstar Trophy Desk Decor | Pop Idol Collectible Figure | Fan Award Statue',           'Gold trophy-style desk figure shaped like a microphone on a star base, with a faux marble plinth engraved with the phrase Born to Shine. A playful self-gifting or fan gifting piece.',                                                              'Material: Poly-resin cast body + faux marble PVC base | Height: ~22 cm | Finish: Metallic gold spray paint + polished base | Engraving: Born to Shine lettering on plinth | Weight: ~380 g | Packaging: Foam-protected gift box',                  'Pop fans, gifting, music lovers, desk decor',               1199.00, 1899.00, 37, 4.6, 200,  'images/products/pop/20.jpg', 38, FALSE, FALSE, TRUE,  FALSE);



-- ============================================================
-- SECTION 5: Movies PRODUCTS  (category_id = 4)
-- Images: images/products/movies/1.jpg to 22.jpg
-- Total : 22 products
-- ============================================================
INSERT INTO products (product_name, category_id, key_words, description, specifications, ideal_for, price, mrp, discount, rating, reviews, image_link, stock, is_new, is_popular, is_recommended, show_on_home) VALUES

('Marvel Character Cushion Covers',    4, 
 'Marvel Superhero Cushion Cover Set | Avengers Home Decor Pillows',
 'Iconic superhero name and design cushion covers adding bold comic-inspired style to your sofa, bed, or gaming room. Vibrant sublimation print.',
 'Material: 100% Polyester microfiber | Size: 40 x 40 cm | Print: All-over sublimation with superhero name and symbol | Closure: Hidden zipper | Thread count: 200TC | Care: Machine washable cold | Pack: Sold individually',
 'Marvel fans, home decor, collectors',
 499.00, 899.00, 44, 4.6, 540, 'images/products/movies/1.jpg', 60, FALSE, TRUE, FALSE, TRUE),

('Avengers Varsity Jacket',            4, 
 'Marvel Avengers Varsity Jacket | Superhero Streetwear Jacket',
 'Stylish varsity jacket with Avengers branding and classic sporty color blocking. A wearable fandom statement for Marvel fans who want to look the part.',
 'Material: Cotton blend outer + soft fleece lining | Closure: Front zip + snap buttons | Cuffs: Ribbed elastic knit | Collar: Ribbed rib knit | Print: Avengers chest logo + back graphic | Sizes: S-XXL | Weight: ~450 g',
 'Marvel fans, casual fashion streetwear',
 1899.00, 2999.00, 37, 4.7, 420, 'images/products/movies/2.jpg', 35, TRUE, TRUE, TRUE, TRUE),

('Avengers Cap and Hoodie Set',        4, 
 'Marvel Avengers Hoodie & Cap Combo | Superhero Apparel Set',
 'Combo set including an Avengers-printed hoodie and a matching adjustable cap. Both feature coordinated Marvel branding for the ultimate fan look.',
 'Hoodie: Cotton fleece blend, front kangaroo pocket, drawstring hood | Cap: Structured 6-panel with adjustable snap back | Print: Matching Avengers logo on both | Sizes: S-XXL hoodie | Cap: One size fits most | Set weight: ~600 g',
 'Marvel fans, casual wear, gifting',
 1499.00, 2499.00, 40, 4.6, 310, 'images/products/movies/3.jpg', 40, FALSE, FALSE, FALSE, TRUE),

('Marvel Character Keychain Set',      4, 
 'Marvel Superhero Metal Keychain Set | Collectible Key Rings',
 'Premium collection of Marvel-themed keychains with detailed miniature superhero designs. Each keychain features a different Avengers character.',
 'Material: Zinc alloy metal | Finish: Painted enamel + polished metal details | Characters: Iron Man, Captain America, Thor, Spider-Man, Hulk | Size: ~5-6 cm each | Ring: Stainless steel | Pack: 5 keychains | Weight: ~25 g each',
 'Marvel fans, bag accessories',
 399.00, 799.00, 50, 4.5, 620, 'images/products/movies/4.jpg', 50, FALSE, FALSE, FALSE, FALSE),

('Marvel AirPods Silicone Case',       4, 
 'Marvel Superhero AirPods Case | Silicone Earbud Protection Case',
 'Marvel-themed silicone case designed to protect AirPods while showing off your superhero fandom. Shockproof with keychain loop for easy carrying.',
 'Material: Food-grade liquid silicone | Compatibility: AirPods Gen 1/2/3 | Drop protection: 1.5 m drop tested | Characters: Multiple hero designs available | Keychain loop: Attached metal D-ring | Dimensions: ~7 x 5 x 3 cm',
 'Tech accessories, Marvel fans',
 349.00, 699.00, 50, 4.5, 410, 'images/products/movies/5.jpg', 55, FALSE, FALSE, FALSE, FALSE),

('Iron Man Collectible Figure Set',    4, 
 'Iron Man Action Figure Collectible Set | Marvel Display Statue',
 'Highly detailed Iron Man figure set with multiple suit accessories and dynamic pose options. Multiple Iron Man armors recreated in premium detail.',
 'Material: PVC/ABS composite | Height: ~20 cm main figure | Suit: Mark 50 armor with removable helmet | Accessories: 3 alternate hand poses + arc reactor display | Paint: Metallic red and gold airbrush | Weight: ~350 g | Collector box',
 'Collectors, Marvel fans, display shelves',
 2499.00, 3999.00, 38, 4.8, 210, 'images/products/movies/6.jpg', 18, TRUE, FALSE, TRUE, TRUE),

('Marvel Superhero Display Figures',   4, 
 'Marvel Avengers Premium Display Figures | Superhero Statue Collection',
 'High-quality set of Marvel superhero statues with dynamic action poses designed for collectors and permanent display shelves.',
 'Material: Resin/PVC blended composite | Height: ~25 cm each | Figures: Avengers core team 4-piece set | Base: Individual branded circular bases | Paint: Semi-gloss premium finish | Pack: 4 figures boxed | Weight: ~250 g each',
 'Collectors, Marvel fans',
 3499.00, 5499.00, 36, 4.8, 190, 'images/products/movies/7.jpg', 15, FALSE, TRUE, FALSE, FALSE),

('Spider-Man Action Statue',           4, 
 'Spider-Man Dynamic Action Figure | Marvel Collectible Statue',
 'Spider-Man in a mid-air swinging pose with sculpted web effects. The dynamic stance and translucent web strands make this a standout collector piece.',
 'Material: Cold-cast Resin | Height: ~24 cm | Pose: Mid-air swinging action | Web effect: Translucent stretched PVC web strand | Base: Building ledge scenic base | Paint: Classic red-blue with web line detail | Weight: ~400 g',
 'Marvel collectors, Spider-Man fans',
 2199.00, 3599.00, 39, 4.7, 230, 'images/products/movies/8.jpg', 20, FALSE, FALSE, TRUE, TRUE),

('Iron Man Arc Reactor Lamp',          4, 
 'Iron Man Arc Reactor LED Display Lamp | Marvel Desk Decor',
 'LED display lamp inspired by Tony Stark arc reactor with a circular glowing blue light and detailed outer casing. A must-have Marvel desk piece.',
 'Material: Acrylic + ABS casing | LED color: Cool blue glow | Power: USB 5V | Diameter: ~12 cm | Depth: ~5 cm | Mount: Freestanding on base | Switch: Push button on back | Brightness: Fixed | Weight: ~280 g | Cord: 1 m',
 'Marvel fans, desk decor, Iron Man collectors',
 1199.00, 1999.00, 40, 4.7, 460, 'images/products/movies/9.jpg', 38, TRUE, TRUE, TRUE, TRUE),


('Marvel Character Phone Case with Figure Topper',   4, 'Marvel Avengers 3D Figure Phone Case | Iron Man Captain America Spider-Man Black Panther Cover | Superhero Mobile Case',          'Fun Marvel phone cases featuring bold character icons on the back with an adorable 3D mini figure perched on the top edge. Each case showcases a different hero with their signature colour and symbol.',                                            'Material: Soft TPU case + ABS figure topper | Compatibility: Multiple models available (specify at order) | Characters: Iron Man, Captain America, Spider-Man, Black Panther, Groot | Case finish: Matte smooth surface | Figure: Removable clip-on topper | Drop protection: 1 m | Weight: ~40 g',                    'Marvel fans, phone accessories, gifting',            599.00,  999.00,  40, 4.6, 530,  'images/products/movies/10.jpg', 55, FALSE, TRUE,  FALSE, TRUE),

('Harry Potter Dark Arts Insulated Water Bottle',    4, 'Harry Potter Dark Arts Steel Water Bottle | Hogwarts 20oz Insulated Bottle | Wizarding World Drinkware',                          'Sleek black insulated water bottle featuring an all-over Harry Potter Dark Arts crest design in deep gold. Keeps drinks cold for hours and is perfect for Potterheads on the go.',                                                                  'Material: Double-walled 304 Stainless Steel | Capacity: 600 ml (20 oz) | Insulation: Keeps cold 16h, hot 8h | Lid: Screw-top sport cap with carry loop | Print: All-over wraparound Dark Arts crest in gold | Finish: Matte black | Care: Hand wash only | Weight: ~320 g',                                         'Harry Potter fans, daily use, gifting',              1299.00, 1999.00, 35, 4.7, 460,  'images/products/movies/11.jpg', 48, FALSE, TRUE,  TRUE,  TRUE),

('Hogwarts House Striped Tie Set',                   4, 'Harry Potter Hogwarts House Tie Set | Gryffindor Slytherin Ravenclaw Hufflepuff Necktie | Cosplay Accessory',                    'Set of four satin-finish striped ties representing all four Hogwarts houses, each embroidered with the official house crest. Perfect for cosplay, school uniform looks, or as a Potterhead fashion accessory.',                                    'Material: Polyester satin weave | Length: ~57 cm | Width: 6.5 cm at widest | Closure: Pre-knotted with adjustable elastic loop | Houses: Gryffindor (red/gold), Slytherin (green/silver), Ravenclaw (blue/silver), Hufflepuff (yellow/navy) | Embroidery: Woven house crest near tip | Pack: 4 ties | Weight: ~80 g total', 'Potterheads, cosplay, gifting, fans',                899.00,  1499.00, 40, 4.7, 380,  'images/products/movies/12.jpg', 60, FALSE, FALSE, TRUE,  TRUE),

('Harry Potter Chibi Characters Fleece Hoodie',      4, 'Harry Potter Chibi Cast Hoodie | Wizarding World Graphic Sweatshirt | Potterhead Casual Wear',                                    'Cosy black heavyweight fleece hoodie featuring a cute chibi-style group print of Harry, Ron, Hermione, Dumbledore, Hagrid, and Hedwig on the chest. Brushed fleece inner lining for extra warmth.',                                               'Material: 60% Cotton + 40% Polyester fleece | Weight: 380 GSM heavyweight | Inner: Brushed warm fleece lining | Print: Chibi cast group graphic on chest | Fit: Regular unisex | Hood: Adjustable drawstring | Pocket: Front kangaroo | Sizes: S-XXL | Care: Machine wash cold inside out',                         'Harry Potter fans, casual wear, gifting',            1499.00, 2299.00, 35, 4.8, 620,  'images/products/movies/13.jpg', 50, TRUE,  TRUE,  TRUE,  TRUE),

('Harry Potter Hogwarts House iPhone Silicone Case', 4, 'Harry Potter Hogwarts House Crest iPhone Case | Slytherin Gryffindor Soft Silicone Cover | Wizarding World Phone Accessories',   'Soft silicone iPhone cases featuring intricate Hogwarts house crest artwork surrounded by magical icons like wands, potions, and spell books. Available in Slytherin black and Gryffindor burgundy.',                                              'Material: Liquid silicone soft shell | Compatibility: iPhone 14 Pro / 14 Pro Max (specify model at order) | Houses: Slytherin (black) and Gryffindor (burgundy) | Print: Full wrap-around detailed crest artwork | Camera protection: Raised lip around lens | Drop protection: 1.5 m | Weight: ~35 g',              'Harry Potter fans, iPhone users, gifting',           699.00,  1199.00, 42, 4.6, 410,  'images/products/movies/14.jpg', 52, FALSE, TRUE,  FALSE, TRUE),

('Harry Potter Wizard Chess Set',                    4, 'Harry Potter Wizard Chess Set | Wizarding World Chess Board Game | Collectible Strategy Game',                                   'The iconic Wizard Chess Set from Harry Potter brought to life with 32 detailed stone-finish resin chess pieces styled like medieval wizard characters. Includes a foldable chess board, all pieces, and a Harry Potter Wizard Chess guidebook.',   'Material: Resin chess pieces + foldable cardboard chess board | Pieces: 32 total (16 per side in grey and dark blue-black finish) | Board: 32 x 32 cm foldable | Guidebook: Harry Potter Wizard Chess rules and lore booklet | Ages: 8+ | Weight: ~600 g | Packaging: Collector window box',                          'Harry Potter fans, board game lovers, gifting',      1999.00, 3199.00, 37, 4.8, 540,  'images/products/movies/15.jpg', 35, FALSE, TRUE,  TRUE,  TRUE),

('Hogwarts Castle 3D Resin Tankard Mug',             4, 'Harry Potter Hogwarts Castle 3D Relief Tankard | Resin Sculpted Mug with Dragon Handle | Wizarding World Premium Drinkware',    'Stunning premium tankard mug with a fully sculpted 3D Hogwarts castle in raised relief wrapping around the exterior. Features a detailed coiling dragon as the handle and a stainless steel inner cup for practical use.',                         'Material: Resin outer body + 304 Stainless Steel inner cup | Capacity: ~400 ml | Handle: Fully sculpted 3D dragon coil | Exterior: Hand-painted Hogwarts castle in stone and bronze tones | Inner: Removable stainless steel cup | Care: Hand wash only | Weight: ~650 g | Dimensions: ~12 x 14 cm',               'Harry Potter collectors, premium gifting, display',  1799.00, 2799.00, 36, 4.9, 390,  'images/products/movies/16.jpg', 28, TRUE,  TRUE,  TRUE,  TRUE),

('Pirates of the Caribbean Skull Key Collectible',   4, 'Pirates of the Caribbean Skull Sword Key Collectible | Jack Sparrow Metal Key Replica | Movie Collectible Gift Box',             'Detailed antique-brass metal key replica featuring a skull topped with a pirate hat, crossed swords, and a classic key shaft. Inspired by Pirates of the Caribbean and presented in a premium red velvet gift box.',                              'Material: Zinc alloy metal | Finish: Antique brass patina | Key Height: ~12 cm | Design: Skull + pirate hat + crossed sabre detail on bow | Gift box: Red rigid gift box with red velvet inlay | Weight: ~90 g | Usage: Display / collectible only',  'Pirates of the Caribbean fans, collectors, gifting', 799.00,  1299.00, 38, 4.7, 310,  'images/products/movies/17.jpg', 45, FALSE, FALSE, TRUE,  TRUE),

('Jack Sparrow Funko Pop Special Edition',           4, 'Jack Sparrow Funko Pop #1482 Special Edition | Pirates of the Caribbean Vinyl Figure | Disney Collector Toy',                  'Special Edition Funko Pop vinyl figure of Captain Jack Sparrow from Pirates of the Caribbean. Number 1482 in the Funko Pop series, featuring Jack in his iconic pirate outfit with rum bottle and signature braided hair.',                        'Material: Vinyl | Height: ~9.5 cm | Figure: Jack Sparrow #1482 | Edition: Funko Special Edition exclusive | Base: Branded circular display base | Packaging: Pirates of the Caribbean themed window collector box | Detail: Accurate costume and accessories | Weight: ~100 g',                                      'Pirates of the Caribbean fans, Funko collectors',   1499.00, 2299.00, 35, 4.8, 470,  'images/products/movies/18.jpg', 30, TRUE,  TRUE,  FALSE, TRUE),

('Mission Impossible Final Reckoning Duffel Bag',    4, 'Mission Impossible The Final Reckoning Duffel Bag | Tom Cruise Movie Merch Gym Bag | Official Film Merchandise',               'Official Mission Impossible The Final Reckoning branded duffel bag in sleek matte black with bold red logo print. Sturdy construction with padded shoulder strap, top carry handles, and red zipper detail for the agent on the move.',            'Material: Heavy-duty PVC coated polyester | Capacity: ~30 litres | Dimensions: ~50 x 26 x 26 cm | Handles: Top carry handles + detachable padded shoulder strap | Closure: Red zip main compartment | Print: Mission Impossible The Final Reckoning front logo | Weight: ~550 g',                                   'Movie fans, gym use, travel, gifting',               1699.00, 2599.00, 35, 4.6, 220,  'images/products/movies/19.jpg', 35, TRUE,  FALSE, TRUE,  TRUE),

('Mission Impossible Ceramic Mug',                   4, 'Mission Impossible Logo Ceramic Mug | IMF Movie Fan Coffee Mug | Black 330ml Drinkware',                                        'Sleek gloss black ceramic mug featuring the iconic Mission Impossible logo with bold red box and the clever MISSION. IMpossible strikethrough typography. A stylish daily mug for fans of the franchise.',                                        'Material: High-grade gloss ceramic | Capacity: 330 ml | Print: Mission Impossible logo on front face | Mug colour: Gloss black | Handle: Ergonomic C-handle | Care: Microwave safe + dishwasher safe | Dimensions: ~9 x 8 cm | Weight: ~300 g',     'Mission Impossible fans, office use, gifting',       499.00,  899.00,  44, 4.5, 280,  'images/products/movies/20.jpg', 60, FALSE, FALSE, FALSE, TRUE),

('Fantastic Four Funko Pop Set of 4',                4, 'Fantastic Four Funko Pop Complete Set | Mr Fantastic Invisible Woman Human Torch The Thing Vinyl Figures | Marvel Collectors Set', 'Complete set of all four Fantastic Four members as Funko Pop vinyl figures. Includes Mr. Fantastic, Invisible Woman, Human Torch with flame effect, and The Thing with rocky texture — all in their classic blue suits.',                       'Material: Vinyl | Height: ~9.5 cm each | Figures: Mr. Fantastic + Invisible Woman + Human Torch + The Thing | Human Torch: Translucent flame effect body | The Thing: Textured rocky orange sculpt | Base: Branded circular display base per figure | Pack: 4 figures | Weight: ~100 g each | Packaging: Individual window boxes', 'Marvel fans, Fantastic Four collectors, display', 3499.00, 5499.00, 36, 4.8, 340,  'images/products/movies/21.jpg', 22, TRUE,  TRUE,  TRUE,  TRUE);



-- ============================================================
-- SECTION 5: Series PRODUCTS  (category_id = 4)
-- Images: images/products/series/1.jpg to 13.jpg 
-- Total: 13 products
-- ============================================================

INSERT INTO products (product_name, category_id, key_words, description, specifications, ideal_for, price, mrp, discount, rating, reviews, image_link, stock, is_new, is_popular, is_recommended, show_on_home) VALUES

('Stranger Things Hoodie',             5, 
 'Stranger Things Logo Hoodie | Netflix Series Sweatshirt',
 'Stylish hoodie with the iconic Stranger Things retro logo. The distressed font and vintage red-on-black design captures the 80s Hawkins vibe perfectly.',
 'Material: 65% Cotton + 35% Polyester fleece | Weight: 300 GSM | Print: Large logo front chest print in vintage distressed red | Hood: Drawstring adjustable | Pocket: Front kangaroo | Sizes: S-XXL | Care: Machine wash cold',
 'Stranger Things fans, casual wear, gifting',
 1299.00, 2099.00, 38, 4.6, 420, 'images/products/series/1.jpg', 40, FALSE, TRUE, FALSE, TRUE),

('Stranger Things Character Sweatshirts', 5, 
 'Stranger Things Character Sweatshirt Collection | Fan Apparel',
 'Cozy sweatshirts featuring fan-favorite Stranger Things characters. Each sweatshirt focuses on one character with a dedicated artwork and quote.',
 'Material: Cotton blend | Weight: 280 GSM | Print: Character-specific artwork + name on chest | Fit: Regular | Style: Crewneck sweatshirt | Interior: Brushed soft fleece | Sizes: S-XXL | Colors: Navy, Grey, Black options',
 'Fans, casual fashion, Netflix series lovers',
 1199.00, 1999.00, 40, 4.5, 350, 'images/products/series/2.jpg', 38, FALSE, FALSE, FALSE, FALSE),

('Stranger Things Mini Backpack',      5, 
 'Stranger Things Retro Mini Backpack | Netflix Series Bag',
 'Compact mini backpack with Stranger Things retro graphics. Stylish faux leather construction with adjustable straps, perfect for students or casual days.',
 'Material: PU faux leather | Dimensions: 28 x 22 x 10 cm | Capacity: ~8 liters | Straps: Padded adjustable shoulder straps | Closure: Top zip main compartment + front zip pocket | Print: Retro series graphic | Weight: ~400 g',
 'Students, fans, casual travel days',
 1399.00, 2199.00, 36, 4.6, 260, 'images/products/series/3.jpg', 32, TRUE, FALSE, FALSE, TRUE),

('Stranger Things Funko Display Frame', 5, 
 'Stranger Things Funko Pop Wall Display Frame | Collector Showcase',
 'Decorative wooden wall frame designed to showcase multiple Stranger Things Funko Pop figures with a clear acrylic front panel protecting the figures.',
 'Material: MDF wood frame + clear acrylic front | Capacity: Holds 6 standard Funko Pop boxes | Dimensions: ~60 x 40 cm | Mounting: Wall screws included | Depth: 15 cm per shelf | Finish: Black matte painted | Weight: ~1.2 kg',
 'Funko Pop collectors, display decor',
 1999.00, 3199.00, 37, 4.7, 180, 'images/products/series/4.jpg', 20, FALSE, FALSE, TRUE, FALSE),

('Nevermore Academy Mug',              5, 
 'Wednesday Nevermore Academy Coffee Mug | Gothic Series Merchandise',
 'Ceramic mug inspired by the Nevermore Academy crest from Wednesday. Clean gothic design with the school motto and raven emblem on a black background.',
 'Material: High-grade ceramic | Capacity: 330 ml | Print: Nevermore crest + motto wrap-around design | Color: Black mug + white/gold print | Handle: Standard C-handle | Care: Microwave + dishwasher safe | Weight: ~290 g',
 'Wednesday fans, gothic aesthetic lovers',
 399.00, 699.00, 43, 4.5, 210, 'images/products/series/5.jpg', 45, FALSE, TRUE, FALSE, TRUE),

('Wednesday Backpack',                 5, 
 'Wednesday Addams Gothic Backpack | Series Merchandise',
 'Sleek all-black backpack inspired by Wednesday gothic aesthetic. Minimal design with subtle series branding, suitable for school or casual outings.',
 'Material: PU leather | Dimensions: 38 x 28 x 12 cm | Capacity: ~20 liters | Straps: Padded adjustable + chest strap | Compartments: 1 main + 1 front + 2 side pockets | Closure: YKK zipper | Print: Wednesday logo tag | Weight: ~600 g',
 'Students, Wednesday fans, gothic style lovers',
 1499.00, 2299.00, 35, 4.6, 190, 'images/products/series/6.jpg', 28, FALSE, FALSE, FALSE, FALSE),

('Wednesday Charm Keychain',           5, 
 'Wednesday Addams Charm Keychain | Gothic Accessory',
 'Gothic-inspired charm keychain featuring motifs from the Wednesday series including the hand and raven. Durable metal alloy with dark enamel finish.',
 'Material: Zinc alloy metal | Finish: Dark gunmetal + black enamel | Charms: Wednesday hand + raven + Nevermore crest | Size: ~6 cm total length | Ring: Stainless steel split ring | Weight: ~20 g | Pack: 1 keychain',
 'Wednesday fans, gothic accessories',
 299.00, 599.00, 50, 4.4, 160, 'images/products/series/7.jpg', 60, FALSE, FALSE, FALSE, TRUE),

('Wednesday Mini Figure Collection',  5, 
 'Wednesday Series Mini Figure Set | Collectible Display Figures',
 'Mini collectible figures from the Wednesday series featuring main characters in their iconic looks and outfits from the Netflix show.',
 'Material: PVC plastic | Height: ~7 cm each | Characters: Wednesday, Enid, Tyler, Xavier, Bianca | Paint: Accurate outfit color detail | Base: Individual flat display bases | Pack: 5 figure set | Weight: ~25 g each',
 'Collectors, Wednesday fans, Netflix lovers',
 899.00, 1499.00, 40, 4.6, 200, 'images/products/series/8.jpg', 30, FALSE, FALSE, FALSE, FALSE),

('The Boys Graphic T-Shirt',           5, 
 'The Boys Character Graphic T-Shirt | TV Series Apparel',
 'Bold graphic tee inspired by The Boys characters. Distressed artwork print with the Vought International aesthetic captures the dark satirical tone of the show.',
 'Material: 100% Combed Cotton | Weight: 185 GSM | Print: Large front character artwork in distressed style | Neckline: Classic crew neck | Fit: Regular unisex | Sizes: S-XXL | Care: Machine wash cold, do not tumble dry',
 'The Boys fans, casual wear, TV series lovers',
 799.00, 1299.00, 38, 4.6, 260, 'images/products/series/9.jpg', 50, FALSE, TRUE, FALSE, TRUE),

('Squid Game Funko Pop Figures',       5, 
 'Squid Game Character Funko Pop Collection',
 'Funko Pop vinyl figures of iconic Squid Game characters including Player 456, the Front Man, and the Guards in their signature costumes.',
 'Material: Vinyl | Height: ~9.5 cm each | Characters: Player 456, Front Man, Guard, Player 067 | Base: Branded circular display base | Packaging: Window display box | Detail: Accurate costume and helmet sculpt | Weight: ~100 g each',
 'Squid Game fans, Funko collectors',
 1999.00, 3299.00, 39, 4.7, 220, 'images/products/series/10.jpg', 22, TRUE, TRUE, TRUE, TRUE),

('Squid Game Bottle and Mug Set',      5, 
 'Squid Game Themed Bottle & Mug Combo | Series Merchandise',
 'Matching drinkware set featuring Squid Game branding. Insulated steel bottle keeps drinks cold and the ceramic mug features the iconic circle-triangle-square symbols.',
 'Bottle: 304 Stainless Steel, 500 ml, keeps cold 12h | Mug: Ceramic 330 ml | Both: Squid Game symbol print (circle, triangle, square) | Mug care: Microwave + dishwasher safe | Bottle: Hand wash only | Gift box included',
 'Squid Game fans, drinkware gift sets',
 899.00, 1499.00, 40, 4.6, 190, 'images/products/series/11.jpg', 30, FALSE, FALSE, FALSE, FALSE),

('Squid Game Doll Alarm Clock',        5, 
 'Squid Game Young-Hee Doll Alarm Clock | LED Desk Clock',
 'Fun desk alarm clock inspired by the iconic Young-Hee doll from Squid Game. Features LED digital display, multiple alarm modes, and a creepy accurate doll sculpt.',
 'Material: ABS plastic | Display: LED digital clock | Functions: Time + Date + Alarm + Snooze | Doll Height: ~15 cm | Power: 3x AA batteries (not included) | Sound: Electronic beep alarm | Color: Yellow dress White face | Weight: ~250 g',
 'Squid Game fans, desk decor, gift ideas',
 1299.00, 2099.00, 38, 4.6, 150, 'images/products/series/12.jpg', 26, FALSE, FALSE, TRUE, TRUE),

('Alice in Borderland Funko Figures',  5, 
 'Alice in Borderland Character Funko Pop Set',
 'Vinyl Funko Pop figures of Alice in Borderland main characters Arisu and Usagi in their survival game outfits. Accurate sculpt with game-world details.',
 'Material: Vinyl | Height: ~9.5 cm each | Characters: Arisu (Ryohei Arisu) + Usagi (Yuzuha Usagi) | Base: Branded circular base | Packaging: Window collector box | Sculpt: Survival outfit accurate detail | Weight: ~100 g each',
 'Alice in Borderland fans, Funko collectors',
 1799.00, 2999.00, 40, 4.7, 140, 'images/products/series/13.jpg', 20, FALSE, FALSE, FALSE, TRUE);


 -- NOTE:
-- Music page should combine category_id 6 and 7 dynamically.
-- Movies & Series page should combine category_id 4 and 5 dynamically.
-- Do NOT duplicate products into category_id 3 or 8 for display purposes.